### PR TITLE
fix(ci): fix sanity check and run for PRs

### PR DESCRIPTION
**Pull request by wilsonianb**
## Changes proposed in this pull request

- Build accounts service before running connector tests.
- Run sanity check for pull requests (to avoid unexpected failures after merging to `main`).

## Checklist

- [ ] Related issues linked using `fixes #number`
- [ ] Tests added/updated
- [x] Documentation added
- [x] Make sure that all checks pass

### CODE REVIEW

**Review by sentientwaffle — APPROVED** [review]

**Review by cairin — COMMENTED** [review]
Why do we need to build the accounts service before running tests in the connector?

**Comment by sentientwaffle** [comment]
I think the packages' `package.json`'s need a `prepare` script to build. That way when the connector "installs" the accounts service, it will make sure its compiled.

**Comment by wilsonianb** [comment]
Will the `prepare` script help with our zero-install setup?
I tried it, but running `yarn install --immutable --immutable-cache` doesn't appear to build the accounts service:
https://github.com/wilsonianb/rafiki/pull/5/commits/9991ec553b48109eefd697d545e842abe66b0053

**Comment by sentientwaffle** [comment]
Interesting. It might be due to the `immutable`/`immutable-cache`... I guess the explicit building of `accounts` is necessary after all.

**Comment by wilsonianb** [comment]
I'm seeing if jest can be configured to build accounts for us with something like `moduleNameMapper`
https://medium.com/ah-technology/a-guide-through-the-wild-wild-west-of-setting-up-a-mono-repo-part-2-adding-jest-with-a-breeze-16e08596f0de

**Comment by wilsonianb** [comment]
I haven't been able to get `ts-jest` to compile `accounts` when running `connector` tests.
There's a related discussion here: https://github.com/kulshekhar/ts-jest/issues/1648
I vote we keep manually building for now but keep an eye out for a better `ts-jest` solution.

**Pull request merged**
